use std::collections::HashMap;

/// Base WAF fingerprinting module detecting Cloudflare, AWS WAF, and Akamai.
/// Uses response heuristics to identify protection mechanisms.
pub struct WafDetector {
    signatures: HashMap<WafVendor, WafSignature>,
}

impl WafDetector {
    pub fn new() -> Self {
        let mut signatures = HashMap::new();
        
        // Cloudflare signatures
        signatures.insert(WafVendor::Cloudflare, WafSignature {
            header_patterns: vec!["cf-ray", "cf-cache-status", "server: cloudflare"],
            status_codes: vec![403, 503],
            body_patterns: vec!["cf-browser-verification", "Checking your browser"],
        });

        // AWS WAF signatures
        signatures.insert(WafVendor::AwsWaf, WafSignature {
            header_patterns: vec!["x-amzn-requestid", "x-amz-cf-id"],
            status_codes: vec![403, 405],
            body_patterns: vec!["AWS WAF", "Access Denied", "Generated by cloudfront"],
        });

        // Akamai signatures
        signatures.insert(WafVendor::Akamai, WafSignature {
            header_patterns: vec!["x-akamai-transformed", "x-check-cache-status"],
            status_codes: vec![400, 403, 406],
            body_patterns: vec!["AkamaiGHost", "Reference ID"],
        });

        // Imperva/Incapsula
        signatures.insert(WafVendor::Imperva, WafSignature {
            header_patterns: vec!["x-iinfo", "incap_ses"],
            status_codes: vec![403, 405],
            body_patterns: vec!["Incapsula", "Visalidation Failed"],
        });

        // F5 BigIP
        signatures.insert(WafVendor::F5BigIp, WafSignature {
            header_patterns: vec!["x-wa-info", "x-bigip-server"],
            status_codes: vec![403],
            body_patterns: vec!["BigIP", "Request rejected"],
        });

        Self { signatures }
    }

    /// Detect WAF from response headers and body.
    pub fn detect(&self, headers: &[httparse::Header], status: u16, body: &[u8]) -> Vec<WafDetectionResult> {
        let mut results = Vec::new();
        let body_str = std::str::from_utf8(body).unwrap_or("");

        for (vendor, signature) in &self.signatures {
            let mut score = 0;

            // Check header patterns
            for pattern in &signature.header_patterns {
                if pattern.contains(':') {
                    let parts: Vec<&str> = pattern.splitn(2, ':').collect();
                    if parts.len() == 2 {
                        let header_name = parts[0].trim().to_lowercase();
                        let header_value = parts[1].trim().to_lowercase();
                        
                        for header in headers {
                            if header.name.eq_ignore_ascii_case(&header_name) 
                                && std::str::from_utf8(header.value).unwrap_or("")
                                    .to_lowercase()
                                    .contains(&header_value) 
                            {
                                score += 2;
                            }
                        }
                    }
                } else {
                    // Just check header name exists
                    for header in headers {
                        if header.name.eq_ignore_ascii_case(pattern) {
                            score += 1;
                        }
                    }
                }
            }

            // Check status code
            if signature.status_codes.contains(&status) {
                score += 1;
            }

            // Check body patterns
            for pattern in &signature.body_patterns {
                if body_str.contains(pattern) {
                    score += 2;
                }
            }

            if score > 0 {
                results.push(WafDetectionResult {
                    vendor: *vendor,
                    confidence: self.calculate_confidence(score),
                    score,
                });
            }
        }

        // Sort by confidence descending
        results.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));
        results
    }

    fn calculate_confidence(&self, score: i32) -> f32 {
        // Normalize to 0.0 - 1.0 range
        (score.min(10) as f32) / 10.0
    }

    /// Check if a specific WAF is present.
    pub fn is_protected(&self, vendor: WafVendor, headers: &[httparse::Header], status: u16, body: &[u8]) -> bool {
        let results = self.detect(headers, status, body);
        results.iter().any(|r| r.vendor == vendor && r.confidence > 0.7)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WafVendor {
    Cloudflare,
    AwsWaf,
    Akamai,
    Imperva,
    F5BigIp,
    Unknown,
}

#[derive(Debug)]
pub struct WafSignature {
    pub header_patterns: Vec<&'static str>,
    pub status_codes: Vec<u16>,
    pub body_patterns: Vec<&'static str>,
}

#[derive(Debug)]
pub struct WafDetectionResult {
    pub vendor: WafVendor,
    pub confidence: f32,
    pub score: i32,
}

impl Default for WafDetector {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cloudflare_detection() {
        let detector = WafDetector::new();
        let headers = [
            httparse::Header { name: "cf-ray", value: b"abc123" },
            httparse::Header { name: "server", value: b"cloudflare" },
        ];

        let results = detector.detect(&headers, 200, b"");
        assert!(results.iter().any(|r| r.vendor == WafVendor::Cloudflare));
    }

    #[test]
    fn test_aws_waf_detection() {
        let detector = WafDetector::new();
        let headers = [
            httparse::Header { name: "x-amz-cf-id", value: b"xyz789" },
        ];
        let body = b"Access Denied";

        let results = detector.detect(&headers, 403, body);
        assert!(results.iter().any(|r| r.vendor == WafVendor::AwsWaf));
    }
}
